version: '2'
services:
  blue-server:
    container_name: blue-server
    image: almgergo/aws-test:latest
    ports:
      - 8080:8080
  green-server:
    container_name: green-server
    image: almgergo/aws-test:latest
    ports:
      - 8090:8080
  proxy:
    container_name: nginx-proxy
    build: ./nginx
    image: reverse-proxy
    ports:
      - 80:80
      - 443:443
